### ISSUE TITLE
Clarify and document (or fully automate) dependencies 

### ISSUE THREAD

**Issue by mactyr** [energyPATHWAYS/energyPATHWAYS#9]
As a novice developer
I want the readme to clearly explain what version of python and associated packages are required to run energyPATHWAYS
so that I can do an initial test run without delay and feel confident that the software is well-documented and supported

**AC**
1. README.md should document that python 2.7 is required for reasons of library compatibility.
2. README.md should note that energyPATHWAYS was developed and tested using Anaconda (with a link to their site) and that it works well with the default Anaconda environment.
3. README.md should document which packages must be in the environment before running setup.py (and if possible setup.py should validate that these are present before running) _or_ setup.py should be updated to install all necessary packages correctly, eliminating the external dependencies (see below).

**Background on AC3**

Currently if I set up an "empty" anaconda environment (without the default packages), clone a fresh copy of the repo and run `python setup.py develop`, several packages install correctly but then there is a failure attempting to install scipy (trace below). If I `conda install numpy` and then re-run setup.py, the scipy installation gets farther but errors out for lack of a fortran compiler (trace below below). I also encountered these issues during my initial attempt to set up energyPATHWAYS using my macports python environment (prior to switching to anaconda).

We should choose an approach to resolving this before working this ticket. Documenting dependencies and asking users to install packages using a third-party tool (e.g. anaconda) reduces our development effort and probably makes package installation more reliable, since such tools are widely used and well-tested. On the other hand, I presume that fixing up setup.py so it can handle all dependencies gives us finer control over package versions, if we should need that... but it's also somewhat reinventing the wheel. Both ways have pros and cons so some discussion is warranted.

First error:

```
Searching for scipy
Reading https://pypi.python.org/simple/scipy/
Best match: scipy 0.17.0
Downloading https://pypi.python.org/packages/source/s/scipy/scipy-0.17.0.zip#md5=28a4fe29e980804db162524f10873211
Processing scipy-0.17.0.zip
Writing /var/folders/jz/2f93p0d125344s5ggky1mt0h0000gn/T/easy_install-JqrYgH/scipy-0.17.0/setup.cfg
Running scipy-0.17.0/setup.py -q bdist_egg --dist-dir /var/folders/jz/2f93p0d125344s5ggky1mt0h0000gn/T/easy_install-JqrYgH/scipy-0.17.0/egg-dist-tmp-jYCMmj
Traceback (most recent call last):
  File "setup.py", line 16, in <module>
    'profilehooks'
  File "/Users/michael/anaconda/envs/empty/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/Users/michael/anaconda/envs/empty/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/Users/michael/anaconda/envs/empty/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/Users/michael/anaconda/envs/empty/lib/python2.7/site-packages/setuptools-19.4-py2.7.egg/setuptools/command/develop.py", line 34, in run
  File "/Users/michael/anaconda/envs/empty/lib/python2.7/site-packages/setuptools-19.4-py2.7.egg/setuptools/command/develop.py", line 133, in install_for_development
  File "/Users/michael/anaconda/envs/empty/lib/python2.7/site-packages/setuptools-19.4-py2.7.egg/setuptools/command/easy_install.py", line 720, in process_distribution
  File "/Users/michael/anaconda/envs/empty/lib/python2.7/site-packages/setuptools-19.4-py2.7.egg/pkg_resources/__init__.py", line 827, in resolve
  File "/Users/michael/anaconda/envs/empty/lib/python2.7/site-packages/setuptools-19.4-py2.7.egg/pkg_resources/__init__.py", line 1072, in best_match
  File "/Users/michael/anaconda/envs/empty/lib/python2.7/site-packages/setuptools-19.4-py2.7.egg/pkg_resources/__init__.py", line 1084, in obtain
  File "/Users/michael/anaconda/envs/empty/lib/python2.7/site-packages/setuptools-19.4-py2.7.egg/setuptools/command/easy_install.py", line 640, in easy_install
  File "/Users/michael/anaconda/envs/empty/lib/python2.7/site-packages/setuptools-19.4-py2.7.egg/setuptools/command/easy_install.py", line 670, in install_item
  File "/Users/michael/anaconda/envs/empty/lib/python2.7/site-packages/setuptools-19.4-py2.7.egg/setuptools/command/easy_install.py", line 853, in install_eggs
  File "/Users/michael/anaconda/envs/empty/lib/python2.7/site-packages/setuptools-19.4-py2.7.egg/setuptools/command/easy_install.py", line 1081, in build_and_install
  File "/Users/michael/anaconda/envs/empty/lib/python2.7/site-packages/setuptools-19.4-py2.7.egg/setuptools/command/easy_install.py", line 1067, in run_setup
  File "/Users/michael/anaconda/envs/empty/lib/python2.7/site-packages/setuptools-19.4-py2.7.egg/setuptools/sandbox.py", line 242, in run_setup
  File "/Users/michael/anaconda/envs/empty/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/michael/anaconda/envs/empty/lib/python2.7/site-packages/setuptools-19.4-py2.7.egg/setuptools/sandbox.py", line 195, in setup_context
  File "/Users/michael/anaconda/envs/empty/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/michael/anaconda/envs/empty/lib/python2.7/site-packages/setuptools-19.4-py2.7.egg/setuptools/sandbox.py", line 166, in save_modules
  File "/Users/michael/anaconda/envs/empty/lib/python2.7/site-packages/setuptools-19.4-py2.7.egg/setuptools/sandbox.py", line 141, in resume
  File "/Users/michael/anaconda/envs/empty/lib/python2.7/site-packages/setuptools-19.4-py2.7.egg/setuptools/sandbox.py", line 154, in save_modules
  File "/Users/michael/anaconda/envs/empty/lib/python2.7/site-packages/setuptools-19.4-py2.7.egg/setuptools/sandbox.py", line 195, in setup_context
  File "/Users/michael/anaconda/envs/empty/lib/python2.7/site-packages/setuptools-19.4-py2.7.egg/setuptools/sandbox.py", line 239, in run_setup
  File "/Users/michael/anaconda/envs/empty/lib/python2.7/site-packages/setuptools-19.4-py2.7.egg/setuptools/sandbox.py", line 269, in run
  File "/Users/michael/anaconda/envs/empty/lib/python2.7/site-packages/setuptools-19.4-py2.7.egg/setuptools/sandbox.py", line 238, in runner
  File "/Users/michael/anaconda/envs/empty/lib/python2.7/site-packages/setuptools-19.4-py2.7.egg/setuptools/sandbox.py", line 46, in _execfile
  File "/var/folders/jz/2f93p0d125344s5ggky1mt0h0000gn/T/easy_install-JqrYgH/scipy-0.17.0/setup.py", line 265, in <module>

  File "/var/folders/jz/2f93p0d125344s5ggky1mt0h0000gn/T/easy_install-JqrYgH/scipy-0.17.0/setup.py", line 253, in setup_package

ImportError: No module named numpy.distutils.core
```

Second error:

```
Could not locate executable gfortran
Could not locate executable f95
Could not locate executable f90
Could not locate executable f77
Could not locate executable xlf90
Could not locate executable xlf
Could not locate executable ifort
Could not locate executable ifc
Could not locate executable g77
Could not locate executable g95
Could not locate executable pgfortran
don't know how to compile Fortran code on platform 'posix'
error: Setup script exited with error: library dfftpack has Fortran sources but no Fortran compiler found
```

**Comment by mactyr** [comment]
QA: @ryandrewjones

**Comment by mactyr** [comment]
Should also note that numexpr 2.4.4 has a bug that causes intermittent inconsistent results (https://github.com/pydata/numexpr/issues/185). Fixed in 2.4.5.

**Comment by mactyr** [comment]
@ryandrewjones, this is ready for your review. Please see the commit referenced above this comment, or equivalently the document_dependencies_9 branch, and let me know if/when you feel it's ready to merge.

**Comment by ryandrewjones** [comment]
@mactyr I've just committed one small change around what packages come with Anaconda by default. Anaconda does include some of the core packages for the project (ex. numpy, scipy, pandas), but doesn't have others (ex. pint). This looks ready to merge now.

**Comment by mactyr** [comment]
Great. I made one more minor change and squashed our changes down to one commit (referenced above) for master, to avoid cluttering the history with tiny readme edits.
